markdown:         rdiscount
pygments:         true
paginate:         4

title:            NetUN的博客
url:              http://netun.github.io
feed:             /atom.xml
author:
    name:         NetUN
    email:        wulijun01234@gmail.com
description:      "NetUN的博客，主要分享关于PHP语言, PHP扩展, Zend引擎, PHP Runtime，JavaScript等Web开发相关技术,新闻和最新动态，以及记录对互联网行业的思考和分析。"
keywords: "PHP,PHP源码分析,PHP扩展,PHP扩展开发,PHP教程,PHP扩展开发教程,PHP内核,PHP内核分析,PHP Runtime,Zend,Zend Engine,PHP Extension,Javascript,CSS,LAMP,风之缘,wulijun01234"
about: 			  "PHP开发者,关注Nginx,PHP等Web开发技术的发展与应用"
follow:
    github:       https://github.com/netun


style: 			 /css/style.css
blogName: 		  NetUN
blogDesc: 		 "PHP语言,PHP扩展,JavaScript等Web开发相关的研究,技术,新闻分享"
